### ISSUE TITLE
Login dialog crashes when you click Cancel

### ISSUE THREAD

**Issue by thatmichaelpark** [sarafec/covered#12]
When I click Log In and then click Cancel in the login dialog, I get:
TypeError: _this2.handleClick is not a function
onClick
src/components/SignIn.js:84
  81 |     label="Cancel"
  82 |     secondary={true}
  83 |     style={styles.button}
> 84 |     onClick={() => this.handleClick(null)}

**Comment by muatasimqazi** [comment]
It's now been been fix.
