### ISSUE TITLE
MyLittleCalendar crashes when coverage object undefined

### ISSUE THREAD

**Issue by sarafec** [sarafec/covered#14]
The MyLittleCalendar component crashes when a team member with no coverage object (on the team) is signed in.  
Below is a picture of the error message - 
  
  
![screen shot 2018-03-11 at 3 23 53 pm](https://user-images.githubusercontent.com/7284217/37259766-de241550-2547-11e8-83e8-584344de92fc.png)

**Comment by thatmichaelpark** [comment]
DataStore.coverageObject was returning undefined if there was no coverage; I changed it to return {} instead in that situation.
